version: '3'
services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${SECRET}
    volumes:
      - 'freespeech-db:/var/lib/postgresql/data'
volumes:
  freespeech-db:
    driver: local
